### ISSUE TITLE
json2yaml line-wraps the output

### ISSUE THREAD

**Issue by cviebrock** [dbohdan/remarshal#5]
Part of my JSON file has the following:

```json
{
  "balanceHeld": {
    "description": "Balance of the account held for transferring to other users (in cents)",
    "type": "integer"
  },
}
```

json2yaml converts this to:

```yaml
balanceHeld:
  description: Balance of the account held for transferring to other users (in
    cents)
  type: integer
```

It looks like all long lines are being wrapped at 80 characters or so.  But that line break that's being added in the `description` property is causing another tool to fail importing, because I don't think wrapping long lines like that results in a valid YAML file.

Could you add a flag to prevent line wrapping? Or output long lines with the "pipe" notation:

```yaml
balanceHeld:
  description: |
    Balance of the account held for transferring to other users (in
    cents)
  type: integer
```
